spring:
  application:
    name: MICROSERVICE

eureka:
  instance:
    instanceId: SERVICE 1
    leaseRenewalIntervalInSeconds: 1
    statusPageUrl: http://www.globo.com.br
  client:   
    healthcheck:
      enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.7.54:9001/eureka
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1
    #Indica que o cliente deve forçar o registro durante a inicialização
    shouldEnforceRegistrationAtInit: true
    eurekaServerReadTimeoutSeconds: 10
    
server:
  port: 8000 