eureka:
  instance:
    instanceId: globo.com
    leaseRenewalIntervalInSeconds: 1
    appname: ABC-SERVICE  
  client:   
    healthcheck:
      enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.7.54:9002/eureka
    eurekaServerReadTimeoutSeconds: 15
    registryFetchIntervalSeconds: 2
    instanceInfoReplicationIntervalSeconds: 2
    initialInstanceInfoReplicationIntervalSeconds: 3
server:
  port: 8000  

