# spring:
#   application:
#     name: service-registry-test2
#   profiles: dev2_profile
# server:
#   port: 8762
# eureka:
#   instance:
#     hostname: localhost
#     appName: ${spring.application.name}
#     #Indica que a  intância é habilitada para o tráfego assim que a instância é registrada no eureka.
#     instanceEnabledOnit: false
#     preferIpAddress: true
#     #Se não for trafegada por requisições seguras
#     securePortEnabled: false
#   client:
#     registerWithEureka: true
#     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:8761/eureka/, http://${eureka.instance.hostname}:${server.port}/eureka/
#     #Indica que o cliente deve forçar o registro durante a inicialização
#     shouldEnforceRegistrationAtInit: true

spring:
  application:
    name: eureka-server-clustered   # ==> This is Service-Id   

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}    
    useDnsForFetchingServiceUrls: true
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false       
    serviceUrl:
      defaultZone: http://192.168.7.54:9001/eureka/