
spring:
  application:
    name: eureka-server-clustered    

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
    appName: ${spring.application.name}
    leaseExpirationDurationInSeconds: 3
    useDnsForFetchingServiceUrls: true
    #indica que a  intância é habilitada para o tráfego assim que a instância é registrada no eureka.
    instanceEnabledOnit: false
    #Se não for trafegada por requisições seguras
    securePortEnabled: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.7.54:9001/eureka/
